import type {
  LabDefinition,
  LessonDefinition,
  LessonParameter,
  LessonPreset,
} from "./lesson-types";
import type { LabId } from "./routes";

const percent = (
  id: string,
  label: string,
  description: string,
  defaultValue: number,
  minimum = 0,
  maximum = 1,
  step = 0.01,
): LessonParameter => ({
  id,
  label,
  description,
  unit: "annual decimal",
  minimum,
  maximum,
  step,
  defaultValue,
  format: "decimal-percent",
});

const number = (
  id: string,
  label: string,
  description: string,
  defaultValue: number,
  minimum: number,
  maximum: number,
  step: number,
  unit = "units",
  format: LessonParameter["format"] = "number",
): LessonParameter => ({
  id,
  label,
  description,
  unit,
  minimum,
  maximum,
  step,
  defaultValue,
  format,
});

const choice = (
  id: string,
  label: string,
  description: string,
  defaultValue: number,
  choices: readonly { readonly value: number; readonly label: string }[],
): LessonParameter => ({
  id,
  label,
  description,
  unit: "named choice",
  minimum: Math.min(...choices.map(({ value }) => value)),
  maximum: Math.max(...choices.map(({ value }) => value)),
  step: 1,
  defaultValue,
  format: "integer",
  choices,
});

const toggle = (
  id: string,
  label: string,
  description: string,
  defaultValue = 1,
): LessonParameter => choice(id, label, description, defaultValue, [
  { value: 1, label: "On" },
  { value: 0, label: "Off" },
]);

const illustrativePreset = (
  values: Readonly<Record<string, number>>,
  label = "Illustrative baseline",
  description = "A transparent classroom example—not a historical estimate.",
): LessonPreset => ({
  id:
    label === "Illustrative baseline"
      ? "illustrative"
      : label.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""),
  label,
  description,
  values,
});

function csvTemplate(
  headers: readonly string[],
  observations: number,
): string {
  const rows = Array.from({ length: observations }, (_, rowIndex) => {
    const date = new Date(Date.UTC(2015, rowIndex, 1))
      .toISOString()
      .slice(0, 10);
    const values = headers.map((_, columnIndex) =>
      (
        0.003 +
        0.012 * Math.sin((rowIndex + 1) * (columnIndex + 1) * 0.37) +
        0.004 * Math.cos((rowIndex + 1) * (columnIndex + 2) * 0.19)
      ).toFixed(6),
    );
    return [date, ...values].join(",");
  });
  return [["date", ...headers].join(","), ...rows].join("\n");
}

function defineLesson(lesson: LessonDefinition): LessonDefinition {
  return lesson;
}

const projectionLessons: readonly LessonDefinition[] = [
  defineLesson({
    id: "jump-diffusion",
    lab: "portfolio-projection",
    release: 1,
    title: "Merton jump diffusion",
    kicker: "When continuous motion is not enough",
    question: "How do rare discontinuous moves reshape the tail of future prices?",
    intuition: "GBM supplies the ordinary wiggle. A Poisson clock adds a separate count of sudden multiplicative jumps, while drift compensation keeps the configured expected return interpretable.",
    equation: "dS/S = (μ − λκ)dt + σdW + (J − 1)dN",
    symbols: [
      { symbol: "λ", meaning: "expected jump arrivals per year" },
      { symbol: "κ", meaning: "expected percentage jump multiplier minus one" },
      { symbol: "J", meaning: "lognormal jump multiplier" },
    ],
    parameters: [
      percent("drift", "Drift", "Continuously compounded annual drift before random shocks.", 0.07, -0.3, 0.4),
      percent("volatility", "Diffusion volatility", "Annual scale of ordinary Gaussian movement.", 0.18, 0, 0.8),
      number("jumpIntensity", "Jump intensity", "Expected arrivals per year.", 0.6, 0, 8, 0.1, "arrivals / year"),
      percent("meanJump", "Mean log jump", "Average log multiplier when an event occurs.", -0.12, -0.8, 0.5),
    ],
    presets: [
      illustrativePreset({ drift: 0.07, volatility: 0.18, jumpIntensity: 0.6, meanJump: -0.12 }),
      illustrativePreset({ drift: 0.07, volatility: 0.18, jumpIntensity: 0, meanJump: -0.12 }, "Turn jumps off", "The limiting case should reproduce the paired GBM path exactly."),
    ],
    workedExample: "With λ = 0, the Poisson count is always zero and the equation collapses path-for-path to GBM under the same diffusion address.",
    check: "Zero jump intensity must reproduce GBM, and empirical arrivals should approach λ over many path-years.",
    assumptions: ["Jump arrivals are Poisson.", "Log jump sizes are independent unless a separate dependence model is supplied.", "Rates and volatility are annual decimals."],
    limitations: ["Real crashes may cluster and co-move across assets.", "Illustrative parameters are not fitted to live data."],
    modelNotePath: "/docs/models/portfolio-market.md#Merton-jump-diffusion",
  }),
  defineLesson({
    id: "garch",
    lab: "portfolio-projection",
    release: 1,
    title: "GARCH(1,1)",
    kicker: "Volatility remembers",
    question: "How can yesterday’s surprise change tomorrow’s conditional variance?",
    intuition: "GARCH makes variance a state variable. Large innovations feed the next variance through α; prior variance persists through β.",
    equation: "hₜ = ω + αε²ₜ₋₁ + βhₜ₋₁",
    symbols: [
      { symbol: "hₜ", meaning: "per-step conditional variance" },
      { symbol: "α", meaning: "news response" },
      { symbol: "β", meaning: "variance persistence" },
    ],
    parameters: [
      number("omega", "Variance intercept ω", "Minimum per-step variance contribution.", 0.00002, 0.000001, 0.001, 0.000001, "variance / step"),
      number("alpha", "News weight α", "Response to the prior squared innovation.", 0.08, 0, 0.5, 0.01, "weight"),
      number("beta", "Persistence β", "Weight on prior conditional variance.", 0.88, 0, 1.1, 0.01, "weight"),
      number("degreesOfFreedom", "Student-t ν", "Degrees of freedom; values above 2 have finite variance.", 7, 3, 40, 1, "degrees", "integer"),
    ],
    presets: [illustrativePreset({ omega: 0.00002, alpha: 0.08, beta: 0.88, degreesOfFreedom: 7 })],
    workedExample: "If α = β = 0, every next variance is simply ω: dynamic volatility becomes constant volatility.",
    check: "For α + β < 1, unconditional variance equals ω / (1 − α − β). At or above one, the lab must warn rather than hide nonstationarity.",
    assumptions: ["Returns use a supplied per-step mean.", "The variance recursion owns volatility when active.", "Student-t innovations are standardized to unit variance."],
    limitations: ["A simple GARCH recursion does not explain why volatility changes.", "Calibration uncertainty can be material in short samples."],
    modelNotePath: "/docs/models/portfolio-market.md#GARCH11",
    dataImport: {
      label: "Fit a monthly return series",
      description: "Columns are date, then one or more simple-return assets. The first asset is fitted; data stays in this browser and is never labeled live.",
      templateFilename: "garch-monthly-returns-template.csv",
      templateCsv: csvTemplate(["Lesson asset"], 120),
    },
  }),
  defineLesson({
    id: "historical-bootstrap",
    lab: "portfolio-projection",
    release: 2,
    title: "Historical bootstrap",
    kicker: "Resample observations, not a fitted curve",
    question: "What paths emerge when we reuse rows from an observed return matrix?",
    intuition: "IID sampling preserves the empirical cross-section. Moving blocks also preserve short runs, making the role of serial dependence visible.",
    equation: "r*ₜ = r_{Iₜ};  Iₜ sampled by row or contiguous block",
    symbols: [
      { symbol: "r*ₜ", meaning: "bootstrapped return row" },
      { symbol: "Iₜ", meaning: "sampled source-row index" },
      { symbol: "b", meaning: "moving-block length" },
    ],
    parameters: [
      choice("bootstrapMethod", "Resampling method", "IID draws individual rows; moving blocks preserve short runs.", 1, [
        { value: 0, label: "IID rows" },
        { value: 1, label: "Moving blocks" },
      ]),
      number("blockSize", "Block size", "Contiguous observations copied together.", 3, 1, 12, 1, "observations", "integer"),
      number("steps", "Path length", "Number of resampled observations.", 24, 6, 120, 1, "steps", "integer"),
    ],
    presets: [
      illustrativePreset({ bootstrapMethod: 1, blockSize: 3, steps: 24 }),
      illustrativePreset({ bootstrapMethod: 0, blockSize: 3, steps: 24 }, "IID rows", "Draw each aligned row independently to remove serial ordering."),
    ],
    workedExample: "A block beginning at source row 5 with b = 3 copies rows 5, 6, and 7 in that order before drawing another start.",
    check: "Every emitted row must exist in the source; within each block, source indexes advance consecutively.",
    assumptions: ["The bundled dataset is illustrative and locally stored.", "Rows are aligned across assets before resampling.", "Sampling uses replacement."],
    limitations: ["The future need not repeat the source distribution.", "Block length is a modeling choice, not a discovered truth."],
    modelNotePath: "/docs/models/portfolio-market.md#Historical-bootstrap",
    dataImport: {
      label: "Resample your aligned returns",
      description: "Use date plus one column per asset. Missing cells are rejected and every sampled row keeps the original cross-asset alignment.",
      templateFilename: "historical-bootstrap-template.csv",
      templateCsv: csvTemplate(["Asset A", "Asset B"], 72),
    },
  }),
  defineLesson({
    id: "retirement-sequence",
    lab: "portfolio-projection",
    release: 2,
    title: "Retirement sequence risk",
    kicker: "Same returns, different order",
    question: "Why can two identical return sets fund very different withdrawals?",
    intuition: "Withdrawals remove capital after each return. Early losses therefore shrink the base that could participate in later gains.",
    equation: "Wₜ = max(0, Wₜ₋₁(1 + rₜ) − Cₜ)",
    symbols: [
      { symbol: "Wₜ", meaning: "wealth after the period-end withdrawal" },
      { symbol: "rₜ", meaning: "simple portfolio return" },
      { symbol: "Cₜ", meaning: "nominal cash withdrawal" },
    ],
    parameters: [
      number("initialCapital", "Starting capital", "Wealth at time zero.", 500000, 10000, 5000000, 10000, "currency", "currency"),
      number("annualContribution", "Annual contribution", "Amount added during the accumulation phase.", 12000, 0, 200000, 1000, "currency / year", "currency"),
      number("accumulationYears", "Years before retirement", "Accumulation years before withdrawals begin.", 10, 0, 40, 1, "years", "integer"),
      number("annualWithdrawal", "Real annual withdrawal", "Time-zero purchasing-power target.", 24000, 0, 200000, 1000, "currency / year", "currency"),
      percent("withdrawalRate", "Percentage withdrawal", "Annual wealth fraction used by the percentage policy.", 0.04, 0, 0.2, 0.005),
      choice("withdrawalPolicy", "Spending policy", "Select how each retirement-period withdrawal is calculated.", 0, [
        { value: 0, label: "Fixed real spending" },
        { value: 1, label: "Percentage of wealth" },
        { value: 2, label: "Guardrail spending" },
      ]),
      percent("inflation", "Inflation", "Annual effective inflation rate.", 0.025, -0.02, 0.15, 0.005),
      percent("stockAllocation", "Stock allocation", "Target capital weight for the higher-volatility asset.", 0.6, 0, 1, 0.05),
      number("rebalanceMonths", "Rebalance interval", "Months between target-weight resets; zero means never.", 12, 0, 60, 1, "months", "integer"),
      number("years", "Retirement horizon", "Years of withdrawals.", 30, 5, 50, 1, "years", "integer"),
    ],
    presets: [
      illustrativePreset({ initialCapital: 500000, annualContribution: 12000, accumulationYears: 10, annualWithdrawal: 24000, withdrawalRate: 0.04, withdrawalPolicy: 0, inflation: 0.025, stockAllocation: 0.6, rebalanceMonths: 12, years: 30 }),
      illustrativePreset({ initialCapital: 500000, annualContribution: 12000, accumulationYears: 10, annualWithdrawal: 24000, withdrawalRate: 0.04, withdrawalPolicy: 2, inflation: 0.025, stockAllocation: 0.6, rebalanceMonths: 12, years: 30 }, "Guardrail spending", "Spending adjusts when its share of current wealth leaves the stated band."),
    ],
    workedExample: "With zero returns, $100 and twelve $1 month-end withdrawals reconcile to $88 exactly. Wealth stops at zero; debt is not silently created.",
    check: "Forward and reversed experiments use the exact same return multiset; only order changes.",
    assumptions: ["Asset returns occur before the period-end cash flow and scheduled rebalance.", "Fixed-real spending rises with inflation; percentage and guardrail rules are explicit alternatives.", "Depleted portfolios cannot become negative."],
    limitations: ["Taxes, fees, pensions, and household choices are omitted.", "Failure probability is not target probability or personal advice."],
    modelNotePath: "/docs/models/risk-retirement.md#Retirement-sequence-risk",
  }),
  defineLesson({
    id: "regime-calibration",
    lab: "portfolio-projection",
    release: 3,
    title: "Regime calibration & provenance",
    kicker: "Labels need an origin story",
    question: "How can returns be grouped into persistent states without pretending labels are observed facts?",
    intuition: "The transparent classroom fitter orders low, middle, and high return bins, then counts transitions. The snapshot records exactly how it was produced.",
    equation: "Pᵢⱼ = (nᵢⱼ + 1) / Σⱼ(nᵢⱼ + 1)",
    symbols: [
      { symbol: "nᵢⱼ", meaning: "observed transitions from state i to state j" },
      { symbol: "+1", meaning: "Laplace smoothing prior" },
    ],
    parameters: [
      number("persistence", "Illustrative persistence", "Probability of remaining in the same state for one step.", 0.88, 0.4, 0.99, 0.01, "one-step probability"),
      number("observations", "Sample size", "Number of illustrative observations shown in provenance.", 120, 12, 1000, 12, "observations", "integer"),
    ],
    presets: [illustrativePreset({ persistence: 0.88, observations: 120 })],
    workedExample: "If a state has 8, 1, and 1 observed destinations, smoothing produces 9/13, 2/13, and 2/13—not absolute certainty.",
    check: "Every transition row sums to one and the snapshot names frequency, return convention, sample dates, method, convergence, and warnings.",
    assumptions: ["State labels are assigned by ordered return groups.", "The one-step transition matrix is not rescaled by the simulator."],
    limitations: ["This teaching classifier is not Baum–Welch maximum likelihood.", "States are model constructs, not directly observed market regimes."],
    modelNotePath: "/docs/models/portfolio-market.md#HMM-and-regime-provenance",
    dataImport: {
      label: "Fit an ordered return regime snapshot",
      description: "Use date and one monthly log-return column. The transparent classroom fitter records the file name and sample window.",
      templateFilename: "regime-log-returns-template.csv",
      templateCsv: csvTemplate(["Lesson asset"], 120),
    },
  }),
  defineLesson({
    id: "student-t",
    lab: "portfolio-projection",
    release: 3,
    title: "Student-t innovations",
    kicker: "Heavier tails with the same variance",
    question: "How does ν change tail frequency while preserving a configured volatility scale?",
    intuition: "A Student-t draw is a normal draw divided by a random scale. Multiplying by √((ν−2)/ν) restores unit variance when ν > 2.",
    equation: "ε = Tν √((ν − 2)/ν)",
    symbols: [
      { symbol: "ν", meaning: "degrees of freedom" },
      { symbol: "Tν", meaning: "raw Student-t variate" },
    ],
    parameters: [
      number("degreesOfFreedom", "Degrees of freedom ν", "Lower values create heavier tails; ν must exceed 2 for finite variance.", 5, 3, 40, 1, "degrees", "integer"),
      number("samples", "Draws", "Fixed-seed sample size for the comparison.", 4000, 500, 20000, 500, "draws", "integer"),
    ],
    presets: [illustrativePreset({ degreesOfFreedom: 5, samples: 4000 })],
    workedExample: "At ν = 5, raw variance is 5/3. The √(3/5) scale returns the innovation variance to one.",
    check: "The empirical variance should stay near one while extreme observations become more common than under a normal innovation.",
    assumptions: ["ν > 2 so variance exists.", "The Student-t is an innovation distribution, not another price process."],
    limitations: ["Symmetric Student-t tails do not capture skew.", "A finite sample may make tail comparisons noisy."],
    modelNotePath: "/docs/models/portfolio-market.md#Student-t-innovations",
  }),
  defineLesson({
    id: "copulas",
    lab: "portfolio-projection",
    release: 3,
    title: "Gaussian & Student-t copulas",
    kicker: "Marginals apart from dependence",
    question: "How can assets share a dependence structure without sharing the same marginal distribution?",
    intuition: "A copula correlates standardized latent innovations. Marginal transforms remain a separate modeling decision.",
    equation: "z = Lε,  LLᵀ = R;  t = z / √(χ²ν/ν)",
    symbols: [
      { symbol: "R", meaning: "positive-semidefinite correlation matrix" },
      { symbol: "L", meaning: "Cholesky factor" },
      { symbol: "ν", meaning: "shared Student-t degrees of freedom" },
    ],
    parameters: [
      number("correlation", "Latent correlation", "Off-diagonal dependence between two assets.", 0.65, -0.95, 0.95, 0.05, "correlation"),
      number("degreesOfFreedom", "Student-t ν", "Shared scale degrees of freedom.", 4, 3, 30, 1, "degrees", "integer"),
      number("samples", "Joint draws", "Fixed-seed sample size.", 3000, 500, 20000, 500, "draws", "integer"),
    ],
    presets: [illustrativePreset({ correlation: 0.65, degreesOfFreedom: 4, samples: 3000 })],
    workedExample: "With R = I, the Cholesky factor is I and Gaussian latent innovations remain independent.",
    check: "The empirical correlation should approach R; a low-ν t copula should show more joint lower-tail observations than its Gaussian counterpart.",
    assumptions: ["R is symmetric and positive semidefinite.", "Diffusion dependence is separate from jump/default dependence."],
    limitations: ["A single static correlation misses changing dependence.", "Copula choice can dominate rare joint-loss estimates."],
    modelNotePath: "/docs/models/portfolio-market.md#Copulas",
  }),
  defineLesson({
    id: "composite-market",
    lab: "portfolio-projection",
    release: 3,
    title: "Sanctioned composite market",
    kicker: "One owner for every parameter",
    question: "What changes when regimes, conditional variance, dependence, and jumps act in a fixed order?",
    intuition: "Composition works only when ownership is explicit: HMM selects drift, GARCH owns variance, the copula owns standardized dependence, and jump diffusion owns discontinuities.",
    equation: "zₜ → μ(zₜ); hₜ ← GARCH; εₜ ← copula; Jₜ ← jumps; Sₜ ← combine",
    symbols: [
      { symbol: "zₜ", meaning: "latent regime" },
      { symbol: "hₜ", meaning: "conditional variance" },
      { symbol: "Jₜ", meaning: "aggregate log jump" },
    ],
    parameters: [
      number("persistence", "Regime persistence", "One-step probability of remaining in the current regime.", 0.9, 0.5, 0.99, 0.01, "probability"),
      number("garchPersistence", "GARCH α + β", "Combined conditional-variance persistence.", 0.94, 0, 1.05, 0.01, "weight"),
      number("correlation", "Diffusion correlation", "Copula correlation between the two assets.", 0.35, -0.9, 0.9, 0.05, "correlation"),
      number("jumpIntensity", "Jump intensity", "Expected independent jumps per asset-year.", 0.4, 0, 5, 0.1, "arrivals / year"),
      toggle("enableRegimes", "Regime switching", "Let the HMM select the active drift."),
      toggle("enableDynamicVariance", "Dynamic variance", "Let GARCH update conditional variance."),
      toggle("enableDependence", "Cross-asset dependence", "Apply the copula correlation instead of independent innovations."),
      toggle("enableJumps", "Jump process", "Add compensated Poisson jump arrivals and sizes."),
    ],
    presets: [
      illustrativePreset({ persistence: 0.9, garchPersistence: 0.94, correlation: 0.35, jumpIntensity: 0.4, enableRegimes: 1, enableDynamicVariance: 1, enableDependence: 1, enableJumps: 1 }),
      illustrativePreset({ persistence: 0.9, garchPersistence: 0.94, correlation: 0.35, jumpIntensity: 0.4, enableRegimes: 0, enableDynamicVariance: 0, enableDependence: 0, enableJumps: 0 }, "All components off", "Recover the simpler constant-variance, independent, no-jump baseline while keeping portfolio accounting active."),
    ],
    workedExample: "Turning jump intensity to zero leaves diffusion addresses untouched; removing a component must recover the corresponding simpler model within tolerance.",
    check: "Diagnostics expose regime, variance, and jump events, and the recorded update order is HMM → GARCH → copula → jump → portfolio.",
    assumptions: ["Heston and GARCH are never active together.", "Jumps are independent across assets in this first composite.", "Every submodel has passed a standalone gate."],
    limitations: ["More mechanisms do not guarantee more truth.", "Parameter uncertainty and structural misspecification remain."],
    modelNotePath: "/docs/models/portfolio-market.md#Sanctioned-composite",
  }),
];

const riskLessons: readonly LessonDefinition[] = [
  defineLesson({
    id: "var-cvar",
    lab: "risk",
    release: 2,
    title: "Value at Risk & CVaR",
    kicker: "A threshold and what lies beyond it",
    question: "How large is a loss threshold, and how severe is the tail after crossing it?",
    intuition: "VaR is a selected loss quantile. Conditional Value at Risk averages losses at or beyond that threshold under an explicit finite-sample rule.",
    equation: "VaR_c = Q_c(L);  CVaR_c = E[L | L ≥ VaR_c]",
    symbols: [
      { symbol: "L", meaning: "loss, where positive values mean loss" },
      { symbol: "c", meaning: "confidence level" },
    ],
    parameters: [
      number("confidence", "Confidence", "Loss quantile to inspect.", 0.95, 0.8, 0.995, 0.005, "probability"),
      number("portfolioValue", "Portfolio value", "Notional value used to convert returns into losses.", 100000, 1000, 10000000, 1000, "currency", "currency"),
      percent("volatility", "Daily volatility", "Per-period standard deviation for the parametric and Monte Carlo methods.", 0.012, 0, 0.1, 0.001),
      number("holdingPeriods", "Holding period", "Square-root-of-time periods in the normal illustration.", 1, 1, 20, 1, "periods", "integer"),
    ],
    presets: [illustrativePreset({ confidence: 0.95, portfolioValue: 100000, volatility: 0.012, holdingPeriods: 1 })],
    workedExample: "For sorted losses [1,2,3,4,5] at 80%, R-7 VaR is 4.2 and the only observation at or above it is 5, so CVaR is 5.",
    check: "For a fixed sample, VaR is monotone in confidence and CVaR is never below VaR.",
    assumptions: ["Positive values are losses.", "The normal method uses arithmetic mean and volatility with square-root-of-time scaling.", "Backtests use only prior observations."],
    limitations: ["VaR says nothing about losses beyond the threshold.", "Small samples make tail averages unstable."],
    modelNotePath: "/docs/models/risk-retirement.md#VaR-and-CVaR",
  }),
  defineLesson({
    id: "risk-backtesting",
    lab: "risk",
    release: 2,
    title: "Risk attribution & backtesting",
    kicker: "A risk number must face new observations",
    question: "Which assets contribute risk, and did the forecast threshold cover losses at the promised rate?",
    intuition: "Euler attribution decomposes parametric VaR. A rolling backtest then freezes each estimation window before observing the next return.",
    equation: "RCᵢ = wᵢ (Σw)ᵢ / σₚ;  breachₜ = 1[Lₜ > VaRₜ|ₜ₋₁]",
    symbols: [
      { symbol: "RCᵢ", meaning: "component risk contribution" },
      { symbol: "Σ", meaning: "return covariance matrix" },
      { symbol: "VaRₜ|ₜ₋₁", meaning: "threshold estimated without the test observation" },
    ],
    parameters: [
      number("stockWeight", "Asset A weight", "Capital allocated to the first asset.", 0.6, 0.05, 0.95, 0.05, "portfolio weight"),
      number("correlation", "Asset correlation", "Dependence used in the covariance matrix.", 0.25, -0.9, 0.9, 0.05, "correlation"),
      number("window", "Estimation window", "Prior observations used for each threshold.", 60, 20, 250, 10, "observations", "integer"),
    ],
    presets: [illustrativePreset({ stockWeight: 0.6, correlation: 0.25, window: 60 })],
    workedExample: "The first test at index 60 may use indexes 0–59, never index 60 itself. This single inequality prevents look-ahead.",
    check: "Component contributions sum back to portfolio volatility/VaR; every estimationEndIndex is less than its testIndex.",
    assumptions: ["Attribution uses a differentiable parametric variance model.", "Backtest observations are time ordered."],
    limitations: ["Passing a coverage test does not prove a model is correct.", "Correlated breaches require richer independence diagnostics."],
    modelNotePath: "/docs/models/risk-retirement.md#Attribution-and-backtesting",
    dataImport: {
      label: "Backtest a time-ordered return series",
      description: "Use date and at least one simple-return column. The first column is tested and every estimation window ends before its test date.",
      templateFilename: "var-backtest-monthly-returns-template.csv",
      templateCsv: csvTemplate(["Portfolio return"], 300),
    },
  }),
];

const constructionLessons: readonly LessonDefinition[] = [
  defineLesson({
    id: "mean-variance",
    lab: "portfolio-construction",
    release: 1,
    title: "Mean–variance optimization",
    kicker: "Return beliefs meet covariance",
    question: "Which long-only weights minimize variance or maximize Sharpe ratio?",
    intuition: "Weights move along a simplex. The covariance matrix bends the risk surface; expected returns tilt the preferred point.",
    equation: "min wᵀΣw;  Σwᵢ=1, wᵢ≥0;  Sharpe=(wᵀμ−r_f)/√(wᵀΣw)",
    symbols: [{ symbol: "w", meaning: "capital weights" }, { symbol: "Σ", meaning: "annual covariance" }, { symbol: "μ", meaning: "annual expected returns" }],
    parameters: [percent("returnA", "Asset A return", "Annual expected arithmetic return.", 0.08, -0.1, 0.3), percent("returnB", "Asset B return", "Annual expected arithmetic return.", 0.04, -0.1, 0.3), percent("correlation", "Correlation", "Dependence between assets.", 0.2, -0.9, 0.9, 0.05), percent("riskFree", "Risk-free rate", "Annual rate used in the Sharpe ratio.", 0.02, -0.05, 0.15)],
    presets: [illustrativePreset({ returnA: 0.08, returnB: 0.04, correlation: 0.2, riskFree: 0.02 })],
    workedExample: "With two uncorrelated equal-volatility assets, the minimum-variance solution is 50% / 50%.",
    check: "Weights are nonnegative and sum to one; reported return and variance recompute from the returned weights.",
    assumptions: ["Expected returns and covariance are supplied annual estimates.", "Portfolios are long-only and fully invested."],
    limitations: ["Small input changes can move optimized weights sharply.", "No turnover, tax, or transaction-cost constraints are included."],
    modelNotePath: "/docs/models/construction.md#Meanvariance-optimization",
  }),
  defineLesson({
    id: "capm",
    lab: "portfolio-construction",
    release: 6,
    title: "CAPM",
    kicker: "One-factor return language",
    question: "How much market sensitivity and unexplained return does an asset exhibit?",
    intuition: "Regression slope is beta; the intercept after accounting for the risk-free rate is alpha. The Security Market Line turns beta into a model-implied expected return.",
    equation: "Rᵢ−r_f = αᵢ + βᵢ(R_m−r_f)+εᵢ",
    symbols: [{ symbol: "β", meaning: "market sensitivity" }, { symbol: "α", meaning: "average excess return not explained by beta" }],
    parameters: [number("beta", "True illustrative beta", "Multiplier used to construct the sample asset returns.", 1.2, -0.5, 2.5, 0.1, "slope"), percent("riskFree", "Risk-free rate", "Per-observation simple rate in the lesson.", 0.001, -0.02, 0.03, 0.001), percent("marketPremium", "Market premium", "Expected market return above the risk-free rate.", 0.006, -0.02, 0.03, 0.001)],
    presets: [illustrativePreset({ beta: 1.2, riskFree: 0.001, marketPremium: 0.006 })],
    workedExample: "If β = 1.2 and the expected market premium is 6%, CAPM adds 7.2% to the risk-free rate.",
    check: "A regression fixture built as asset = α + β×market must recover its α and β.",
    assumptions: ["Returns are aligned and use the same frequency.", "Beta is treated as stable over the fitted sample."],
    limitations: ["A single market factor omits other systematic exposures.", "Historical alpha is not a promise of future outperformance."],
    modelNotePath: "/docs/models/construction.md#CAPM",
  }),
  defineLesson({
    id: "factor-models",
    lab: "portfolio-construction",
    release: 6,
    title: "Factor models",
    kicker: "Explain returns with data-defined drivers",
    question: "Which factor exposures explain an asset’s returns, residual risk, and scenario response?",
    intuition: "Multiple regression estimates a loading for each supplied factor. Nothing in the engine assumes a factor must be market, value, rates, or anything else.",
    equation: "r = α + Bf + ε",
    symbols: [{ symbol: "B", meaning: "estimated factor exposures" }, { symbol: "f", meaning: "aligned factor returns" }, { symbol: "ε", meaning: "residual return" }],
    parameters: [number("marketLoading", "Factor A loading", "Synthetic exposure to the first data-defined factor.", 1.1, -2, 3, 0.1, "loading"), number("styleLoading", "Factor B loading", "Synthetic exposure to the second factor.", 0.4, -2, 3, 0.1, "loading"), percent("scenarioShock", "Factor B shock", "Simple scenario change applied after fitting.", -0.02, -0.15, 0.15, 0.005), number("rollingWindow", "Rolling window", "Prior monthly observations used to estimate each out-of-sample exposure.", 24, 12, 48, 1, "months", "integer")],
    presets: [illustrativePreset({ marketLoading: 1.1, styleLoading: 0.4, scenarioShock: -0.02, rollingWindow: 24 })],
    workedExample: "A 0.4 loading times a −2% factor shock contributes −0.8% before alpha, other factors, and residuals.",
    check: "Synthetic linear data should recover known loadings; rolling estimates must never include future rows.",
    assumptions: ["Asset and factor rows are aligned by timestamp intersection.", "Factors are defined by the dataset, not hard-coded formulas.", "Each rolling test row occurs after its estimation window."],
    limitations: ["Exposures can change over time.", "Regression describes association, not causal truth."],
    modelNotePath: "/docs/models/construction.md#Factor-models",
    dataImport: {
      label: "Align your asset and factor returns",
      description: "Use date, at least one asset: column, and two or more factor: columns. The lesson selects the first asset and first two data-defined factors for a readable rolling comparison.",
      templateFilename: "rolling-factor-returns-template.csv",
      templateCsv: csvTemplate(
        ["asset:Portfolio", "factor:Market", "factor:Value"],
        72,
      ),
    },
  }),
  defineLesson({
    id: "risk-parity",
    lab: "portfolio-construction",
    release: 6,
    title: "Risk parity",
    kicker: "Equal risk is not equal capital",
    question: "Which long-only weights make assets contribute equally to portfolio volatility?",
    intuition: "A low-volatility asset usually needs more capital to carry the same risk contribution as a high-volatility asset.",
    equation: "RCᵢ = wᵢ(Σw)ᵢ/σₚ;  RCᵢ/σₚ = bᵢ",
    symbols: [{ symbol: "RCᵢ", meaning: "asset i volatility contribution" }, { symbol: "bᵢ", meaning: "requested risk budget" }],
    parameters: [percent("volatilityA", "Asset A volatility", "Annual volatility of asset A.", 0.2, 0.01, 0.8), percent("volatilityB", "Asset B volatility", "Annual volatility of asset B.", 0.08, 0.01, 0.8), number("correlation", "Correlation", "Cross-asset return correlation.", 0.15, -0.9, 0.9, 0.05, "correlation")],
    presets: [illustrativePreset({ volatilityA: 0.2, volatilityB: 0.08, correlation: 0.15 })],
    workedExample: "With zero correlation, 20% and 10% volatility assets need roughly 1:2 capital weights to equalize volatility contributions.",
    check: "Risk contributions sum to total portfolio volatility and converge to the requested equal budget.",
    assumptions: ["Covariance is supplied and positive semidefinite.", "Weights are long-only and fully invested."],
    limitations: ["Equal modeled risk is not equal economic importance.", "Covariance estimates may shift in stress."],
    modelNotePath: "/docs/models/construction.md#Risk-parity",
  }),
  defineLesson({
    id: "kelly",
    lab: "portfolio-construction",
    release: 6,
    title: "Kelly criterion",
    kicker: "Growth versus survival",
    question: "What fraction maximizes approximate long-run log growth under explicit caps?",
    intuition: "Kelly rewards excess return and penalizes covariance. Fractional Kelly deliberately gives up theoretical growth to reduce leverage and drawdown sensitivity.",
    equation: "f* ≈ Σ⁻¹(μ−r_f1);  f = qf*, 0<q≤1",
    symbols: [{ symbol: "f*", meaning: "continuous-return Kelly allocation" }, { symbol: "q", meaning: "fractional Kelly multiplier" }],
    parameters: [percent("edgeA", "Asset A excess return", "Annual return above the risk-free rate.", 0.06, -0.1, 0.3), percent("edgeB", "Asset B excess return", "Annual return above the risk-free rate.", 0.025, -0.1, 0.3), number("fraction", "Kelly fraction", "Scale applied to the full-Kelly solution.", 0.5, 0.1, 1, 0.05, "fraction"), number("leverageCap", "Leverage cap", "Maximum total risky allocation.", 1, 0.25, 2, 0.05, "gross weight")],
    presets: [illustrativePreset({ edgeA: 0.06, edgeB: 0.025, fraction: 0.5, leverageCap: 1 })],
    workedExample: "For a binary bet paying net odds b, exact Kelly is (bp−q)/b. A fair coin at even odds gives zero.",
    check: "Full, half, and quarter allocations respect leverage and per-asset caps; the binary fixture matches the exact formula.",
    assumptions: ["The continuous approximation uses expected returns and covariance.", "Leverage and allocation caps are mandatory."],
    limitations: ["Input error can make full Kelly dangerously aggressive.", "The approximation does not represent all path-dependent ruin mechanisms."],
    modelNotePath: "/docs/models/construction.md#Kelly-criterion",
  }),
  defineLesson({
    id: "black-litterman",
    lab: "portfolio-construction",
    release: 6,
    title: "Black–Litterman",
    kicker: "A prior meets explicit views",
    question: "How do market-implied returns change when investor views and confidence are added?",
    intuition: "The model starts with equilibrium returns, then blends absolute or relative views according to their uncertainty before reusing the mean–variance allocator.",
    equation: "μ_BL = [(τΣ)⁻¹ + PᵀΩ⁻¹P]⁻¹[(τΣ)⁻¹π + PᵀΩ⁻¹q]",
    symbols: [{ symbol: "π", meaning: "market-implied equilibrium returns" }, { symbol: "P,q", meaning: "view portfolios and view returns" }, { symbol: "Ω", meaning: "view uncertainty" }],
    parameters: [number("confidence", "View confidence", "How strongly the posterior follows the view.", 0.65, 0.05, 0.95, 0.05, "confidence"), percent("viewReturn", "Relative view", "Expected return of asset A minus asset B.", 0.03, -0.15, 0.15, 0.005), number("tau", "Prior uncertainty τ", "Scale on equilibrium-return uncertainty.", 0.05, 0.005, 0.5, 0.005, "scale")],
    presets: [illustrativePreset({ confidence: 0.65, viewReturn: 0.03, tau: 0.05 })],
    workedExample: "At near-zero confidence, the posterior stays near π. Higher confidence moves Pμ toward q without silently changing the covariance input.",
    check: "Posterior sensitivity is monotone with confidence in a small matrix fixture, and final weights come from the shared allocator.",
    assumptions: ["Market weights and risk aversion define the prior.", "Views are labeled as investor inputs, not estimates."],
    limitations: ["Results depend on τ and view uncertainty choices.", "A polished posterior does not make subjective views objective."],
    modelNotePath: "/docs/models/construction.md#BlackLitterman",
  }),
];

const derivativesLessons: readonly LessonDefinition[] = [
  defineLesson({
    id: "black-scholes",
    lab: "derivatives",
    release: 4,
    title: "Black–Scholes",
    kicker: "An analytical benchmark",
    question: "What is a European option worth under lognormal diffusion and continuous hedging assumptions?",
    intuition: "The formula discounts two probability-weighted terms. Greeks describe local sensitivity—not guaranteed future profit.",
    equation: "C = Se⁻ᑫᵀN(d₁) − Ke⁻ʳᵀN(d₂)",
    symbols: [{ symbol: "S,K", meaning: "spot and strike" }, { symbol: "r,q", meaning: "continuous risk-free and dividend rates" }, { symbol: "σ,T", meaning: "annual volatility and years to expiry" }],
    parameters: [number("spot", "Spot", "Current underlying price.", 100, 20, 250, 1, "currency", "currency"), number("strike", "Strike", "Contract exercise price.", 100, 20, 250, 1, "currency", "currency"), percent("volatility", "Volatility", "Annual lognormal volatility.", 0.2, 0.01, 1), percent("rate", "Risk-free rate", "Continuously compounded annual rate.", 0.04, -0.05, 0.2), percent("dividendYield", "Dividend yield", "Continuous annual dividend yield q.", 0.01, 0, 0.2), number("maturity", "Time to expiry", "Remaining calendar time in years.", 1, 0.02, 5, 0.02, "years"), choice("surfaceDimension", "Sensitivity axis", "Choose which Black–Scholes input varies while the others stay fixed.", 0, [{ value: 0, label: "Spot" }, { value: 1, label: "Volatility" }, { value: 2, label: "Time to expiry" }]), number("comparisonSteps", "CRR steps", "Tree steps used for the same-contract numerical comparison.", 200, 25, 1000, 25, "steps", "integer"), number("comparisonPaths", "Monte Carlo paths", "Fixed-seed trajectories used for the same-contract comparison.", 6000, 1000, 20000, 1000, "paths", "integer")],
    presets: [illustrativePreset({ spot: 100, strike: 100, volatility: 0.2, rate: 0.04, dividendYield: 0.01, maturity: 1, surfaceDimension: 0, comparisonSteps: 200, comparisonPaths: 6000 })],
    workedExample: "Call minus put must equal Se⁻qT − Ke⁻rT. This parity is a stronger check than whether a chart looks plausible.",
    check: "Put–call parity and no-arbitrage bounds must hold; European CRR should approach Black–Scholes and Monte Carlo should report its sampling interval.",
    assumptions: ["European exercise only.", "Constant volatility and rates.", "Continuous dividend yield and compounding."],
    limitations: ["Real implied volatility varies by strike and maturity.", "Continuous frictionless hedging is idealized."],
    modelNotePath: "/docs/models/derivatives.md#BlackScholes",
  }),
  defineLesson({
    id: "binomial-tree",
    lab: "derivatives",
    release: 4,
    title: "Cox–Ross–Rubinstein tree",
    kicker: "Value by backward induction",
    question: "How does an option value emerge one up/down step at a time, including early exercise?",
    intuition: "The tree builds possible underlying prices forward and option values backward. American nodes compare continuation value with immediate exercise.",
    equation: "V = e⁻ʳΔᵗ[pVᵤ + (1−p)V_d];  V_A=max(V, intrinsic)",
    symbols: [{ symbol: "u,d", meaning: "up and down multipliers" }, { symbol: "p", meaning: "risk-neutral up probability" }],
    parameters: [number("spot", "Spot", "Current underlying price.", 100, 20, 250, 1, "currency", "currency"), number("strike", "Strike", "Exercise price.", 105, 20, 250, 1, "currency", "currency"), percent("volatility", "Volatility", "Annual volatility setting tree spacing.", 0.25, 0.01, 1), number("steps", "Tree steps", "Discrete time intervals.", 50, 1, 300, 1, "steps", "integer"), choice("american", "Exercise style", "Choose whether exercise is allowed only at expiry or at any tree node.", 1, [{ value: 0, label: "European" }, { value: 1, label: "American" }])],
    presets: [illustrativePreset({ spot: 100, strike: 105, volatility: 0.25, steps: 50, american: 1 })],
    workedExample: "At each American put node, compare strike − spot with the discounted continuation value; mark early exercise when intrinsic is larger.",
    check: "American value is never below European value; European CRR converges toward Black–Scholes as steps increase.",
    assumptions: ["CRR up/down factors and risk-neutral pricing.", "Tree nodes are retained only for bounded step counts."],
    limitations: ["Coarse trees discretize both time and price.", "Exercise results depend on dividend and rate assumptions."],
    modelNotePath: "/docs/models/derivatives.md#CRR-binomial-tree",
  }),
  defineLesson({
    id: "monte-carlo-options",
    lab: "derivatives",
    release: 4,
    title: "Monte Carlo option pricing",
    kicker: "Price a payoff across paths",
    question: "How can we price path-dependent claims and quantify sampling uncertainty?",
    intuition: "Simulate risk-neutral paths, evaluate each discounted payoff, and report the mean with a standard error and confidence interval.",
    equation: "V̂ = e⁻ʳᵀ(1/n)Σ payoff(pathᵢ);  SE=s/√n",
    symbols: [{ symbol: "n", meaning: "number of simulated paths" }, { symbol: "SE", meaning: "Monte Carlo standard error" }],
    parameters: [number("spot", "Spot", "Initial underlying price.", 100, 20, 250, 1, "currency", "currency"), number("strike", "Strike", "Payoff strike.", 100, 20, 250, 1, "currency", "currency"), percent("volatility", "Volatility", "Annual risk-neutral diffusion volatility.", 0.2, 0.01, 1), number("paths", "Paths", "Fixed-seed sample size.", 5000, 500, 30000, 500, "paths", "integer"), choice("payoff", "Payoff family", "Choose the rule applied to each simulated path.", 1, [{ value: 0, label: "European call" }, { value: 1, label: "Arithmetic Asian call" }, { value: 2, label: "Up-and-out barrier call" }, { value: 3, label: "Fixed-strike lookback" }, { value: 4, label: "Two-asset basket call" }, { value: 5, label: "Floating-strike lookback" }]), number("basketCorrelation", "Basket correlation", "Latent return correlation used only by the two-asset basket.", 0.45, -0.9, 0.9, 0.05, "correlation")],
    presets: [illustrativePreset({ spot: 100, strike: 100, volatility: 0.2, paths: 5000, payoff: 1, basketCorrelation: 0.45 }), illustrativePreset({ spot: 100, strike: 90, volatility: 0.2, paths: 5000, payoff: 4, basketCorrelation: 0.45 }, "Two-asset basket", "A 60/40 weighted basket with explicit cross-asset correlation.")],
    workedExample: "A two-point arithmetic-average call path [100,120] with strike 105 pays max(110−105,0)=5 before discounting.",
    check: "European confidence intervals should cover the analytical benchmark at the documented frequency; variance reduction cannot change the estimand.",
    assumptions: ["Risk-neutral GBM for single assets and the two-asset basket.", "Every stochastic price reports SE and a 95% interval.", "Barrier monitoring is discrete on the visible time grid."],
    limitations: ["Rare barrier events may need far more paths.", "A narrow interval measures sampling error, not model error."],
    modelNotePath: "/docs/models/derivatives.md#Monte-Carlo-pricing",
  }),
  defineLesson({
    id: "heston",
    lab: "derivatives",
    release: 4,
    title: "Heston stochastic volatility",
    kicker: "Variance becomes a process",
    question: "How do mean-reverting variance and correlated shocks alter prices and option values?",
    intuition: "Heston evolves price and variance together. Full truncation uses max(v,0) inside the Euler update so sampled variance stays nonnegative.",
    equation: "dv=κ(θ−v)dt+ξ√v dWᵥ;  corr(dWₛ,dWᵥ)=ρ",
    symbols: [{ symbol: "κ,θ", meaning: "variance mean-reversion speed and level" }, { symbol: "ξ", meaning: "volatility of variance" }, { symbol: "ρ", meaning: "price/variance shock correlation" }],
    parameters: [number("longRunVariance", "Long-run variance θ", "Target variance level.", 0.04, 0.001, 0.5, 0.005, "annual variance"), number("volOfVol", "Volatility of variance ξ", "Randomness in the variance process.", 0.45, 0, 2, 0.05, "annual scale"), number("correlation", "Leverage correlation ρ", "Price/variance shock correlation.", -0.65, -0.95, 0.95, 0.05, "correlation"), number("paths", "Paths", "Fixed-seed pricing sample.", 3000, 500, 20000, 500, "paths", "integer")],
    presets: [illustrativePreset({ longRunVariance: 0.04, volOfVol: 0.45, correlation: -0.65, paths: 3000 })],
    workedExample: "When ξ = 0 and initial variance equals θ, variance is deterministic and the price process approaches constant-volatility GBM.",
    check: "All simulated variances are nonnegative; long-run average tends toward θ and empirical shock correlation tends toward ρ.",
    assumptions: ["Full-truncation Euler discretization.", "Heston and GARCH are not combined."],
    limitations: ["Discretization bias remains at coarse steps.", "No calibration is presented as live."],
    modelNotePath: "/docs/models/derivatives.md#Heston",
  }),
  defineLesson({
    id: "strategy-builder",
    lab: "derivatives",
    release: 4,
    title: "Option strategy builder",
    kicker: "Strategies are sums of legs",
    question: "How do option and underlying legs combine into payoff, P&L, and Greeks?",
    intuition: "A named strategy is not a new pricing formula. Each leg is valued once; cash flows and Greeks add with signed quantities.",
    equation: "Value_strategy = Σ quantityᵢ × valueᵢ",
    symbols: [{ symbol: "quantityᵢ", meaning: "signed long/short leg amount" }, { symbol: "valueᵢ", meaning: "validated value or payoff for leg i" }],
    parameters: [number("spot", "Spot", "Underlying price today.", 100, 20, 250, 1, "currency", "currency"), number("width", "Strike width", "Distance from center strike to wings.", 10, 1, 50, 1, "currency", "currency"), percent("volatility", "Volatility", "Annual volatility shared by the lesson legs.", 0.22, 0.01, 1), choice("strategy", "Strategy", "Choose a named sum of validated option and underlying legs.", 2, [{ value: 0, label: "Covered call" }, { value: 1, label: "Protective put" }, { value: 2, label: "Long straddle" }, { value: 3, label: "Iron condor" }, { value: 4, label: "Long strangle" }, { value: 5, label: "Bull call spread" }])],
    presets: [illustrativePreset({ spot: 100, width: 10, volatility: 0.22, strategy: 2 })],
    workedExample: "A long straddle payoff is max(S−K,0)+max(K−S,0)=|S−K| before subtracting premiums.",
    check: "Aggregated price, payoff, delta, gamma, theta, vega, and rho equal the signed sum of leg values.",
    assumptions: ["Each option leg uses a validated contract convention.", "Payoff and profit/loss are shown separately."],
    limitations: ["Transaction costs and bid/ask spreads are omitted.", "Greeks are local sensitivities and change with market inputs."],
    modelNotePath: "/docs/models/derivatives.md#Strategy-builder",
  }),
];

const ratesCreditLessons: readonly LessonDefinition[] = [
  defineLesson({
    id: "vasicek",
    lab: "rates-credit",
    release: 5,
    title: "Vasicek short rates",
    kicker: "Gaussian mean reversion",
    question: "How does a short rate wander around a long-run level, including below zero?",
    intuition: "The exact transition combines decayed distance from the mean with a Gaussian innovation whose variance has a closed form.",
    equation: "rₜ₊Δ = θ+(rₜ−θ)e⁻κΔ + σ√[(1−e⁻²κΔ)/(2κ)]Z",
    symbols: [{ symbol: "κ", meaning: "mean-reversion speed per year" }, { symbol: "θ", meaning: "long-run annual short rate" }],
    parameters: [percent("initialRate", "Initial short rate", "Annual continuously compounded short rate.", 0.03, 0, 0.2), percent("longRunRate", "Long-run rate", "Risk-neutral mean level shared by both models.", 0.04, 0, 0.2), number("meanReversion", "Mean reversion κ", "Speed per year shared by both models.", 0.7, 0.05, 5, 0.05, "per year"), percent("volatility", "Vasicek volatility", "Annual Gaussian short-rate volatility.", 0.015, 0, 0.1), percent("cirVolatility", "CIR volatility", "Square-root diffusion coefficient; its units differ from Vasicek σ.", 0.1, 0, 0.5), number("maturity", "Bond maturity", "Zero-coupon maturity in years.", 5, 0.25, 30, 0.25, "years")],
    presets: [illustrativePreset({ initialRate: 0.03, longRunRate: 0.04, meanReversion: 0.7, volatility: 0.015, cirVolatility: 0.1, maturity: 5 })],
    workedExample: "As Δ grows, e⁻κΔ shrinks, so the conditional mean forgets today’s rate and approaches θ.",
    check: "Both models use the same execution grid and maturity; negative Vasicek observations, the CIR boundary, bond duration, and convexity stay visible.",
    assumptions: ["Exact Gaussian transition.", "Bond pricing uses risk-neutral parameters and continuous discounting."],
    limitations: ["Gaussian rates can be negative.", "A one-factor short-rate model cannot fit every curve movement."],
    modelNotePath: "/docs/models/rates-credit.md#Vasicek",
  }),
  defineLesson({
    id: "cir",
    lab: "rates-credit",
    release: 5,
    title: "Cox–Ingersoll–Ross",
    kicker: "Square-root rate diffusion",
    question: "How does state-dependent volatility keep a short-rate simulation nonnegative?",
    intuition: "The diffusion scale is proportional to √r, so random motion fades near zero. The Feller condition explains whether zero is theoretically unattainable.",
    equation: "dr = κ(θ−r)dt + σ√r dW;  2κθ ≥ σ²",
    symbols: [{ symbol: "2κθ ≥ σ²", meaning: "Feller condition" }, { symbol: "√r", meaning: "state-dependent diffusion scale" }],
    parameters: [percent("initialRate", "Initial short rate", "Nonnegative annual rate.", 0.03, 0, 0.2), percent("longRunRate", "Long-run rate", "Nonnegative mean level.", 0.04, 0, 0.2), number("meanReversion", "Mean reversion κ", "Speed per year.", 0.8, 0.05, 5, 0.05, "per year"), percent("volatility", "Rate volatility σ", "Square-root diffusion coefficient.", 0.12, 0, 0.5), number("maturity", "Bond maturity", "Zero-coupon maturity in years.", 5, 0.25, 30, 0.25, "years")],
    presets: [illustrativePreset({ initialRate: 0.03, longRunRate: 0.04, meanReversion: 0.8, volatility: 0.12, maturity: 5 })],
    workedExample: "If 2κθ < σ², the Feller condition fails. The lab warns; it does not silently alter σ or θ.",
    check: "Sampled rates stay nonnegative under the documented scheme and analytical bond fixtures agree.",
    assumptions: ["Exact noncentral-chi-square transition sampling.", "Risk-neutral parameters for bond valuation."],
    limitations: ["Exact sampling avoids time-step truncation bias but does not make the one-factor model realistic.", "The Feller condition is informative, not a guarantee of model realism."],
    modelNotePath: "/docs/models/rates-credit.md#CIR",
  }),
  defineLesson({
    id: "nelson-siegel",
    lab: "rates-credit",
    release: 5,
    title: "Nelson–Siegel yield curves",
    kicker: "Level, slope, curvature",
    question: "How can three interpretable factors summarize a cross-section of yields?",
    intuition: "Maturity-dependent loadings turn β₀, β₁, and β₂ into level, slope, and hump-shaped curvature effects.",
    equation: "y(τ)=β₀+β₁(1−e⁻τ/λ)/(τ/λ)+β₂[(1−e⁻τ/λ)/(τ/λ)−e⁻τ/λ]",
    symbols: [{ symbol: "τ", meaning: "maturity in years" }, { symbol: "λ", meaning: "decay controlling curvature location" }],
    parameters: [percent("level", "Level β₀", "Long-maturity yield component.", 0.04, -0.05, 0.2), percent("slope", "Slope β₁", "Short-minus-long component.", -0.02, -0.15, 0.15), percent("curvature", "Curvature β₂", "Medium-maturity hump component.", 0.03, -0.15, 0.15), number("decay", "Decay λ", "Maturity scale in years.", 2, 0.1, 10, 0.1, "years"), percent("shockMagnitude", "Named-shock size", "Annual yield change applied to the selected Nelson–Siegel factor.", 0.01, 0, 0.05, 0.0025)],
    presets: [illustrativePreset({ level: 0.04, slope: -0.02, curvature: 0.03, decay: 2, shockMagnitude: 0.01 })],
    workedExample: "At very long maturity, both decaying loadings approach zero, leaving the curve near β₀.",
    check: "Synthetic yields are recovered within tolerance, and parallel, steepening, flattening, and curvature shocks alter only their named factor.",
    assumptions: ["This is a deterministic curve representation.", "Maturities are measured in years."],
    limitations: ["Static factors are not a stochastic interest-rate model.", "Three factors may miss local curve features."],
    modelNotePath: "/docs/models/rates-credit.md#NelsonSiegel",
  }),
  defineLesson({
    id: "hazard-credit",
    lab: "rates-credit",
    release: 5,
    title: "Hazard-rate credit",
    kicker: "Default as an arrival process",
    question: "How do hazard and recovery change survival probabilities and risky cash flows?",
    intuition: "Cumulative hazard converts an arrival intensity into survival. Expected risky cash flows weight promised payments by survival and recovery by default probability.",
    equation: "S(T)=exp(−∫₀ᵀλ(u)du);  EL=PD×LGD×exposure",
    symbols: [{ symbol: "λ", meaning: "annual default intensity" }, { symbol: "S(T)", meaning: "survival probability" }, { symbol: "LGD", meaning: "one minus recovery fraction" }],
    parameters: [choice("curveType", "Hazard curve", "Choose one constant intensity or an explicit breakpoint with two intensities.", 0, [{ value: 0, label: "Constant" }, { value: 1, label: "Piecewise constant" }]), number("hazard", "Initial hazard", "Annual intensity for the constant curve or first piece.", 0.025, 0, 0.5, 0.005, "per year"), number("longHazard", "Later hazard", "Annual intensity after the breakpoint in piecewise mode.", 0.06, 0, 0.5, 0.005, "per year"), number("breakYear", "Hazard breakpoint", "Year when the later piece begins.", 3, 0.5, 15, 0.5, "years"), number("recovery", "Recovery", "Fraction of face value recovered on default.", 0.4, 0, 1, 0.05, "fraction"), percent("discountRate", "Discount rate", "Annual continuous risk-free discount rate.", 0.035, -0.05, 0.2), number("maturity", "Maturity", "Bond horizon in years.", 5, 0.5, 20, 0.5, "years")],
    presets: [illustrativePreset({ curveType: 0, hazard: 0.025, longHazard: 0.06, breakYear: 3, recovery: 0.4, discountRate: 0.035, maturity: 5 }), illustrativePreset({ curveType: 1, hazard: 0.015, longHazard: 0.06, breakYear: 3, recovery: 0.4, discountRate: 0.035, maturity: 5 }, "Piecewise hazard", "Lower near-term intensity followed by a visible higher long-term segment.")],
    workedExample: "At λ=2% and T=5, survival is e⁻⁰·¹≈90.5%; the five-year default probability is about 9.5%.",
    check: "Constant-hazard survival equals e⁻λT and exact scheduled/recovery cash-flow fixtures reconcile.",
    assumptions: ["Constant or piecewise-constant hazard.", "Recovery convention and discounting are explicit."],
    limitations: ["Default dependence is absent in the first scope.", "Reduced-form probability is not structural Merton probability."],
    modelNotePath: "/docs/models/rates-credit.md#Hazard-rate-credit",
  }),
  defineLesson({
    id: "merton-credit",
    lab: "rates-credit",
    release: 5,
    title: "Merton structural credit",
    kicker: "Equity as a call on firm assets",
    question: "How do firm asset value and debt threshold imply equity, risky debt, and default probability?",
    intuition: "At maturity, equity receives max(V−D,0). That is a call payoff, so Black–Scholes machinery connects the balance sheet to a structural default event.",
    equation: "E = V N(d₁) − De⁻ʳᵀN(d₂);  risky debt = V − E",
    symbols: [{ symbol: "V", meaning: "firm asset value" }, { symbol: "D", meaning: "debt threshold at maturity" }, { symbol: "N(−d₂)", meaning: "risk-neutral maturity default probability" }],
    parameters: [number("assetValue", "Firm asset value", "Modeled market value of firm assets.", 150, 20, 500, 5, "currency", "currency"), number("debt", "Debt threshold", "Promised maturity debt.", 100, 10, 400, 5, "currency", "currency"), percent("assetVolatility", "Asset volatility", "Annual volatility of firm assets.", 0.25, 0.01, 1), percent("rate", "Risk-free rate", "Annual continuous rate.", 0.04, -0.05, 0.2), number("maturity", "Maturity", "Debt horizon in years.", 1, 0.1, 10, 0.1, "years")],
    presets: [illustrativePreset({ assetValue: 150, debt: 100, assetVolatility: 0.25, rate: 0.04, maturity: 1 })],
    workedExample: "Equity plus risky debt must equal firm asset value. This balance-sheet identity holds by construction.",
    check: "Equity matches a call, balance-sheet identities reconcile, and limiting cases behave sensibly.",
    assumptions: ["Firm assets follow GBM under the pricing measure.", "Default occurs only at maturity when assets fall below debt."],
    limitations: ["Real firms can default before one debt maturity.", "Firm asset value and volatility are not directly observed."],
    modelNotePath: "/docs/models/rates-credit.md#Merton-structural-credit",
  }),
];

const tradingLessons: readonly LessonDefinition[] = [
  defineLesson({
    id: "ornstein-uhlenbeck",
    lab: "trading",
    release: 7,
    title: "Ornstein–Uhlenbeck spreads",
    kicker: "A process that pulls toward equilibrium",
    question: "How do configured OU parameters compare with parameters fitted from one finite spread history?",
    intuition: "The distance from equilibrium decays exponentially while Gaussian noise keeps the path uncertain. Fitting reverses the question: estimate that decay from observed consecutive spreads.",
    equation: "Xₜ₊Δ=μ+(Xₜ−μ)e⁻θΔ+σ√[(1−e⁻²θΔ)/(2θ)]Z",
    symbols: [{ symbol: "θ", meaning: "mean-reversion speed" }, { symbol: "ln2/θ", meaning: "half-life" }],
    parameters: [number("initialSpread", "Initial spread", "Spread at time zero.", 1.5, -5, 5, 0.1, "spread units"), number("equilibrium", "Equilibrium", "Long-run modeled mean.", 0, -3, 3, 0.1, "spread units"), number("meanReversion", "Mean reversion θ", "Speed per year.", 1.2, 0.05, 8, 0.05, "per year"), number("volatility", "Spread volatility", "Diffusion scale per square-root year.", 0.7, 0, 3, 0.05, "spread / √year")],
    presets: [illustrativePreset({ initialSpread: 1.5, equilibrium: 0, meanReversion: 1.2, volatility: 0.7 })],
    workedExample: "At θ=1, the expected distance from equilibrium halves after ln2≈0.693 years.",
    check: "Exact conditional moments and half-life agree; fitting warns when the discrete AR coefficient is outside (0,1).",
    assumptions: ["The candidate spread is stationary before OU interpretation.", "Exact Gaussian transition."],
    limitations: ["A spread relationship may break structurally.", "Threshold rules omit costs and execution risk."],
    modelNotePath: "/docs/models/trading.md#OrnsteinUhlenbeck",
  }),
  defineLesson({
    id: "order-book",
    lab: "trading",
    release: 7,
    title: "Limit-order-book engine",
    kicker: "Price first, then time",
    question: "How do limit orders, market orders, and cancellations become trades and a price ladder?",
    intuition: "An incoming order meets the best opposite price first. At the same price, the earliest resting order trades first. Every fill transfers equal cash and inventory.",
    equation: "cash_buyer −= pq; cash_seller += pq; inventory_buyer += q; inventory_seller −= q",
    symbols: [{ symbol: "p,q", meaning: "execution price and quantity" }, { symbol: "price–time", meaning: "best price, then earliest sequence" }],
    parameters: [number("spread", "Opening spread", "Distance between illustrative best bid and ask.", 2, 0.5, 10, 0.5, "price units"), number("depth", "Level depth", "Quantity resting at each side.", 10, 1, 100, 1, "units", "integer"), number("marketSize", "Market order size", "Incoming quantity that consumes asks.", 14, 1, 100, 1, "units", "integer"), number("makerFeeRate", "Maker fee", "Fraction of matched notional charged to the resting order.", 0.0001, 0, 0.01, 0.0001, "fraction of notional", "decimal-percent"), number("takerFeeRate", "Taker fee", "Fraction of matched notional charged to the incoming order.", 0.0005, 0, 0.01, 0.0001, "fraction of notional", "decimal-percent"), number("fixedFee", "Fixed match fee", "Additional amount charged to the taker for each fill.", 0.05, 0, 5, 0.05, "currency", "currency")],
    presets: [illustrativePreset({ spread: 2, depth: 10, marketSize: 14, makerFeeRate: 0.0001, takerFeeRate: 0.0005, fixedFee: 0.05 })],
    workedExample: "Two sell orders at 100 execute in arrival order before any sell order at 101.",
    check: "Replay is identical; cash, inventory, fees, and executed buy/sell quantity reconcile after every event.",
    assumptions: ["Deterministic bounded event engine.", "Negative cash or inventory is allowed as an accounting position, not hidden.", "Maker, taker, and fixed fees are credited to a named collector account."],
    limitations: ["No latency queue or exchange-specific order types.", "The toy book is a mechanism lesson, not calibrated market depth."],
    modelNotePath: "/docs/models/trading.md#Limit-order-book",
  }),
  defineLesson({
    id: "agent-market",
    lab: "trading",
    release: 7,
    title: "Agent-based market",
    kicker: "Rules submit orders; the book decides trades",
    question: "What scenario dynamics emerge when different strategies interact through one validated book?",
    intuition: "Fundamental, trend, market-making, noise, and inventory-balancing agents only decide which orders to submit. They do not bypass execution or accounting.",
    equation: "decision(agent,state) → order event → book → trade → ledger",
    symbols: [{ symbol: "state", meaning: "visible price history and agent inventory" }, { symbol: "ledger", meaning: "cash and inventory after fills" }],
    parameters: [number("fundamentalValue", "Fundamental value", "Illustrative anchor used by one agent.", 102, 80, 120, 1, "price", "currency"), number("noiseAgents", "Noise agents", "Count of uncalibrated random-order strategies.", 3, 1, 12, 1, "agents", "integer"), number("steps", "Event rounds", "Number of deterministic decision rounds.", 12, 3, 40, 1, "rounds", "integer"), number("riskBudget", "Risk budget", "Maximum modeled one-step marked-to-market volatility exposure in cash units.", 2, 0.1, 20, 0.1, "currency risk", "currency"), number("riskLookback", "Risk lookback", "Recent price observations used to estimate one-step volatility.", 8, 2, 30, 1, "observations", "integer"), number("takerFeeRate", "Taker fee", "Fraction of matched notional charged to incoming orders.", 0.0005, 0, 0.01, 0.0001, "fraction of notional", "decimal-percent")],
    presets: [illustrativePreset({ fundamentalValue: 102, noiseAgents: 3, steps: 12, riskBudget: 2, riskLookback: 8, takerFeeRate: 0.0005 })],
    workedExample: "A market maker posts both sides; a fundamental buyer can trade only if an ask is actually resting.",
    check: "Fixed seed replay reproduces decisions, events, trades, fee-aware ledgers, and risk-budget targets; net wealth includes inventory and explicit costs.",
    assumptions: ["Strategies are transparent rules.", "Noise decisions are seeded and addressable.", "The risk-budget agent sizes one asset; it is not mislabeled multi-asset risk parity."],
    limitations: ["Agents are scenarios, not calibrated forecasts of people.", "Simple rules omit learning, latency, and strategic adaptation."],
    modelNotePath: "/docs/models/trading.md#Agent-based-market",
  }),
  defineLesson({
    id: "optimal-execution",
    lab: "trading",
    release: 7,
    title: "Almgren–Chriss execution",
    kicker: "Trade impact against price risk",
    question: "How quickly should a position liquidate when temporary impact and volatility pull in opposite directions?",
    intuition: "Faster trading reduces exposure to price uncertainty but concentrates temporary impact. Risk aversion chooses a point on that frontier.",
    equation: "min E[cost] + λ Var(cost);  x(t)=X sinh(κ(T−t))/sinh(κT)",
    symbols: [{ symbol: "x(t)", meaning: "shares remaining" }, { symbol: "λ", meaning: "risk aversion" }, { symbol: "κ", meaning: "resulting urgency" }],
    parameters: [number("shares", "Shares", "Initial quantity to liquidate.", 100000, 1000, 1000000, 1000, "shares", "integer"), number("intervals", "Intervals", "Discrete trades across the horizon.", 10, 2, 50, 1, "intervals", "integer"), number("riskAversion", "Risk aversion", "Weight on execution-cost variance.", 0.000001, 0, 0.00002, 0.000001, "objective weight"), number("temporaryImpact", "Temporary impact", "Quadratic cost coefficient.", 0.000001, 0.0000001, 0.00001, 0.0000001, "cost coefficient")],
    presets: [illustrativePreset({ shares: 100000, intervals: 10, riskAversion: 0.000001, temporaryImpact: 0.000001 })],
    workedExample: "At zero risk aversion, the temporary-impact-only optimum divides shares evenly across intervals.",
    check: "Inventory begins at X, ends at zero, falls monotonically, and expected cost equals permanent plus temporary components.",
    assumptions: ["Analytical linear-impact model.", "Volatility and impact coefficients are supplied, not calibrated by the book."],
    limitations: ["Real impact can be nonlinear and state dependent.", "The analytical schedule does not guarantee fills in a live book."],
    modelNotePath: "/docs/models/trading.md#AlmgrenChriss",
  }),
];

export const LESSONS: readonly LessonDefinition[] = [
  ...projectionLessons,
  ...riskLessons,
  ...constructionLessons,
  ...derivativesLessons,
  ...ratesCreditLessons,
  ...tradingLessons,
];

export const LABS: readonly LabDefinition[] = [
  {
    id: "portfolio-projection",
    number: "I",
    title: "Portfolio projection",
    subtitle: "Market paths and life-cycle cash flows",
    introduction: "Separate market dynamics from portfolio accounting, then ask how regimes, variance, tails, dependence, and withdrawals change the range of paths.",
    lessonIds: ["accumulation", ...projectionLessons.map((lesson) => lesson.id)],
  },
  {
    id: "portfolio-construction",
    number: "II",
    title: "Portfolio construction",
    subtitle: "From beliefs and covariance to allocation",
    introduction: "Study allocations as constrained mathematical objects. Compare capital weights with the risk and assumptions that produced them.",
    lessonIds: constructionLessons.map((lesson) => lesson.id),
  },
  {
    id: "risk",
    number: "III",
    title: "Risk",
    subtitle: "Loss tails, attribution, and honest backtests",
    introduction: "Define loss first, keep estimation windows separate from tests, and distinguish a threshold from the severity beyond it.",
    lessonIds: riskLessons.map((lesson) => lesson.id),
  },
  {
    id: "derivatives",
    number: "IV",
    title: "Derivatives",
    subtitle: "Analytical, tree, and pathwise valuation",
    introduction: "Price the same European contract three ways before moving into path dependence, stochastic volatility, and composed strategies.",
    lessonIds: derivativesLessons.map((lesson) => lesson.id),
  },
  {
    id: "rates-credit",
    number: "V",
    title: "Rates & credit",
    subtitle: "Discounting, curves, and default mechanisms",
    introduction: "Keep short rates, yields, spreads, survival, and structural default distinct—even when every value is represented by a number.",
    lessonIds: ratesCreditLessons.map((lesson) => lesson.id),
  },
  {
    id: "trading",
    number: "VI",
    title: "Trading mechanics",
    subtitle: "Spreads, books, agents, and execution cost",
    introduction: "Move from a mean-reverting signal into deterministic order matching, then examine how agent rules and impact assumptions shape outcomes.",
    lessonIds: tradingLessons.map((lesson) => lesson.id),
  },
];

export function getLab(id: LabId): LabDefinition {
  return LABS.find((lab) => lab.id === id)!;
}

export function getLesson(lab: LabId, lessonId: string): LessonDefinition {
  return (
    LESSONS.find((lesson) => lesson.lab === lab && lesson.id === lessonId) ??
    LESSONS.find((lesson) => lesson.lab === lab)!
  );
}

export function lessonsForLab(lab: LabId): readonly LessonDefinition[] {
  return LESSONS.filter((lesson) => lesson.lab === lab);
}
